"""empty message

Revision ID: 418690bf6f81
Revises: ca1624623af2
Create Date: 2026-03-09 21:11:44.482918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '418690bf6f81'
down_revision: Union[str, None] = 'ca1624623af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_token_id'), 'password_reset_tokens', ['token_id'], unique=False)
    op.add_column('dreams', sa.Column('owner_id', sa.String(length=36), nullable=False))
    op.add_column('dreams', sa.Column('person_type', sa.Enum('veteran', 'elderly', 'child', 'animal_shelter', 'other', name='persontype'), nullable=False))
    op.drop_constraint('dreams_dreamer_id_fkey', 'dreams', type_='foreignkey')
    op.create_foreign_key(None, 'dreams', 'users', ['owner_id'], ['user_id'])
    op.drop_column('dreams', 'dreamer_id')
    op.drop_column('users', 'person_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('person_type', postgresql.ENUM('VETERAN', 'ELDERLY', 'CHILD', 'ANIMAL_SHELTER', 'OTHER', name='persontype'), autoincrement=False, nullable=True))
    op.add_column('dreams', sa.Column('dreamer_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dreams', type_='foreignkey')
    op.create_foreign_key('dreams_dreamer_id_fkey', 'dreams', 'users', ['dreamer_id'], ['user_id'])
    op.drop_column('dreams', 'person_type')
    op.drop_column('dreams', 'owner_id')
    op.drop_index(op.f('ix_password_reset_tokens_token_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
