"""initial

Revision ID: 962df0248daf
Revises: 
Create Date: 2026-03-02 22:06:29.026662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962df0248daf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('DREAMER', 'ADMIN', 'DONOR', name='userrole'), nullable=False),
    sa.Column('person_type', sa.Enum('VETERAN', 'ELDERLY', 'CHILD', 'ANIMAL_SHELTER', 'OTHER', name='persontype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('dreams',
    sa.Column('dream_id', sa.String(length=36), nullable=False),
    sa.Column('dreamer_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('participation_format', sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='participationformat'), nullable=False),
    sa.Column('target_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dreamer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dream_id')
    )
    op.create_index(op.f('ix_dreams_dream_id'), 'dreams', ['dream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dreams_dream_id'), table_name='dreams')
    op.drop_table('dreams')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
