"""empty message

Revision ID: fda31fcbcf76
Revises: aaa07826875a
Create Date: 2026-03-13 09:49:33.535886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda31fcbcf76'
down_revision: Union[str, None] = 'aaa07826875a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreams', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('dreams', sa.Column('image_url', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dreams', 'image_url')
    op.drop_column('dreams', 'city')
    # ### end Alembic commands ###
